
/*
--CREAMOS LA TABLA CLIENTES

CREATE TABLE ar_clientes(
cliente_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
tipo_documento  VARCHAR2(5)    NOT NULL,
num_documento   VARCHAR2(30)   NOT NULL,
nombre          VARCHAR2(40)   NOT NULL,
segmento        VARCHAR2(30)   DEFAULT 'PYME' NOT NULL,
estado          VARCHAR2(15)   DEFAULT 'ACTIVO' NOT NULL,

--CONSTRAINTS
--Primero las llaves
CONSTRAINT pk_ar_clientes PRIMARY KEY (cliente_id),
CONSTRAINT uq_ar_clientes_doc UNIQUE (tipo_documento, num_documento),
CONSTRAINT ck_ar_clientes_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);*/

/*
--CREAMOS TABLA FACTURAS
CREATE TABLE ar_facturas(
factura_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
cliente_id          NUMBER NOT NULL,
num_factura         VARCHAR2(40) NOT NULL,
fecha_emision       DATE NOT NULL,
fecha_vencimiento   DATE NOT NULL,
monto_total NUMBER (12,2) NOT NULL,

--CONSTRAINTS
--Primero las llaves
CONSTRAINT pk_ar_facturas PRIMARY KEY (factura_id),
CONSTRAINT uq_ar_facturas_num UNIQUE (num_factura),
CONSTRAINT fk_ar_facturas_cliente FOREIGN KEY (cliente_id) REFERENCES ar_clientes (cliente_id),
CONSTRAINT ck_ar_facturas_fechas CHECK (fecha_emision <= fecha_vencimiento),
CONSTRAINT ck_ar_facturas_monto CHECK (monto_total >= 0)
);*/


/*
--CREAMOS TABLA PAGOS
CREATE TABLE  ar_pagos(
pagos_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
factura_id  NUMBER NOT NULL,
monto_pago  NUMBER (12,2) NOT NULL,

--CONSTRAINTS
CONSTRAINT pk_ar_pagos PRIMARY KEY (pagos_id),
CONSTRAINT fk_ar_pagos_factura FOREIGN KEY (factura_id) REFERENCES ar_facturas (factura_id),
CONSTRAINT ck_ar_pagos_monto CHECK (monto_pago > 0)
);*/

/*
--CREAMOS TABLA NOTAS CRÉDITO
CREATE TABLE ar_notas_credito(
notas_credito_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
factura_id          NUMBER NOT NULL,
motivo              VARCHAR2(40) DEFAULT 'ABONO' NOT NULL,

--CONSTRAINTS
CONSTRAINT pk_ar_notas_credito PRIMARY KEY (notas_credito_id),
CONSTRAINT fk_ar_notas_credito_facturas FOREIGN KEY (factura_id) REFERENCES ar_facturas (factura_id)
);*/



--AGREGAR UNA NUEVA COLUMNA A LAS NOTAS CRÉDITO, CON LA FINALIDAD DE INCORPORAR LA OPCIÓN DE DEVOLUCIONES

--Primero agregamos la columna permitiendo el null (ALter a nivel de estructura)
ALTER TABLE ar_notas_credito
ADD devolucion NUMBER (12,2);

--De segunda rellenamos el histórico (update a nivel de registro)
UPDATE ar_notas_credito
SET devolucion = 0
WHERE devolucion IS NULL;

--De terceras cambiamos la posibilidad de que sea Nula
ALTER TABLE ar_notas_credito
MODIFY devolucion NOT NULL;

COMMIT;

--QUEREMOS MODIFICAR UN REGISTRO DE LA TABLA PAGOS, EL ID DE LA FACTURA EN ESE REGISTRO NO SE CORRESPONDE CON EL NÚMERO DE FACTURA
UPDATE ar_pagos
SET factura_id = (SELECT factura_id FROM ar_facturas WHERE num_factura = 'F-1003')
WHERE factura_id = 9;

ROLLBACK;


--NOS EQUIVOCAMOS EN EL NOMBRE DEL CLIENTE CON UN CLIENTE_ID DETERMINADO. HACEMOS LA CORRECIÓN
UPDATE ar_clientes
SET nombre = 'John Doe'
WHERE cliente_id = 33;

COMMIT;

*/

--MODIFICAR LA TABLA FACTURAS AGREGAR LA COLUMNA DEL ESTADO DEL PAGO

--1. CREAR LA NUEVA COLUMNA
ALTER TABLE ar_facturas
ADD estado_pago VARCHAR2 (15);

--3. CREAMOS LAS RESTRICCIONES DESPUÉS DE ACTUALIZAR LA INFORMACIÓN YA CONSIGNADA EN LA TABLA
ALTER TABLE ar_facturas
ADD CONSTRAINT ck_ar_facturas_estado_pago
CHECK (estado_pago IN ('PAGADA', 'NO PAGADA'));

ALTER TABLE ar_facturas
MODIFY estado_pago NOT NULL;

--AGREGAR LAS COLUMNAS DE FECHAS A LAS TABLAS DE PAGOS Y NOTAS CRÉDITO
ALTER TABLE ar_pagos
ADD fecha_pago DATE;

ALTER TABLE ar_notas_credito
ADD fecha_nota DATE;

--MODIFICAMOS LAS COLUMNAS DE FECHA PARA QUE SEAN NO NULAS

ALTER TABLE ar_pagos
MODIFY fecha_pago NOT NULL;

ALTER TABLE ar_notas_credito
MODIFY fecha_nota NOT NULL;

COMMIT;



/***********************************************************
                    EJERCICIO HOTEL/AIRBNB
************************************************************/

CREATE TABLE ht_huespedes(
    huesped_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_doc    VARCHAR2(5)     NOT NULL,
    num_doc     VARCHAR2(20)    NOT NULL,
    nombre      VARCHAR2(30)    NOT NULL,
    email       VARCHAR2(30),
    estado      VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    --CONTRAINTS/RESTRICCIONES

    CONSTRAINT pk_ht_huespedes PRIMARY KEY (huesped_id),
    CONSTRAINT uq_ht_huesped_doc UNIQUE (tipo_doc, num_doc),
    CONSTRAINT ck_ht_huesped_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
    );
    
CREATE TABLE ht_habitaciones (
    habitacion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    num_habitacion  VARCHAR2(10) NOT NULL,
    tipo            VARCHAR2(20) NOT NULL,
    precio_noche    NUMBER(10,2) NOT NULL,
    estado          VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,

    --CONTRAINTS/RESTRICCIONES

    CONSTRAINT pk_ht_habitaciones PRIMARY KEY (habitacion_id),
    CONSTRAINT uq_ht_hab_num UNIQUE (num_habitacion),
    CONSTRAINT ck_ht_hab_estado CHECK (estado IN ('DISPONIBLE', 'RESERVADA')),
    CONSTRAINT ck_hab_precio CHECK (precio_noche >= 0)
    );    
    
CREATE TABLE ht_reservas (
    reserva_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    huesped_id      NUMBER NOT NULL,
    habitacion_id   NUMBER NOT NULL,
    fecha_ingreso   DATE NOT NULL,
    fecha_salida    DATE NOT NULL,
    monto_total     NUMBER (12,2) NOT NULL,
    estado          VARCHAR2(10) DEFAULT 'ACTIVA',
 
    --CONTRAINTS/RESTRICCIONES

    CONSTRAINT pk_ht_reservas PRIMARY KEY (reserva_id),
    CONSTRAINT fk_ht_res_huesped FOREIGN KEY (huesped_id)
        REFERENCES ht_huespedes (huesped_id),
    CONSTRAINT fk_ht_res_habitacion FOREIGN KEY (habitacion_id)
        REFERENCES ht_habitaciones (habitacion_id),
    CONSTRAINT ck_ht_res_fecha CHECK (fecha_salida > fecha_ingreso),
    CONSTRAINT ck_ht_res_monto CHECK (monto_total >= 0),
    CONSTRAINT ck_ht_res_estado CHECK (estado IN ('ACTIVA', 'CANCELADA', 'TERMINADA', 'NO LLEGÓ'))
    );     

CREATE TABLE ht_pagos(
    pago_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id  NUMBER NOT NULL,
    fecha_pago  DATE NOT NULL,
    monto_pago  NUMBER(12,2) NOT NULL,
    canal_pago  VARCHAR2(30) DEFAULT 'TARJETA DE CRÉDITO' NOT NULL,
    referencia  VARCHAR2(50),

    --CONTRAINTS/RESTRICCIONES

    CONSTRAINT pk_ht_pagos PRIMARY KEY (pago_id),
    CONSTRAINT fk_ht_pagos_res FOREIGN KEY (reserva_id)
        REFERENCES ht_reservas (reserva_id),
    CONSTRAINT ck_ht_pago_monto CHECK (monto_pago >= 0)
    );  
    
CREATE TABLE ht_notas_cancelacion (
    nota_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id          NUMBER NOT NULL,
    fecha_nota          DATE NOT NULL,
    monto_devolucion    NUMBER(12,2) NOT NULL,
    motivo              VARCHAR(30) DEFAULT 'CANCELACION' NOT NULL,

    --CONTRAINTS/RESTRICCIONES

    CONSTRAINT pk_ht_notas PRIMARY KEY (nota_id),
    CONSTRAINT fk_ht_notas_res FOREIGN KEY (reserva_id)
        REFERENCES ht_reservas (reserva_id),
    CONSTRAINT ck_ht_nota_monto CHECK (monto_devolucion >= 0)
    );   

COMMIT;


/***********************************************************
                    EJERCICIO CORE STUDIO
************************************************************/

--ELIMINAR TABLAS ANTERIORES
DROP TABLE cs_notas_cancelacion;
DROP TABLE cs_pagos;
DROP TABLE cs_reservas;

DROP TABLE cs_clases;

DROP TABLE cs_clientes;
DROP TABLE cs_entrenadores;

--CREAR NUEVAS TABLAS
--Entrenadores
CREATE TABLE cs_entrenadores (
    entrenador_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_entrenador VARCHAR2(30) NOT NULL,
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_entrenadores PRIMARY KEY (entrenador_id)
);

--Clientes
CREATE TABLE cs_clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_doc   VARCHAR2(5)  NOT NULL,
    num_doc    VARCHAR2(20) NOT NULL,
    nombre     VARCHAR2(30) NOT NULL,
    email      VARCHAR2(30),
    telefono   VARCHAR2(15),
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_clientes     PRIMARY KEY (cliente_id),
    CONSTRAINT uq_cs_clientes_doc UNIQUE (tipo_doc, num_doc)
);

--Clases
CREATE TABLE cs_clases (
    clase_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    entrenador_id NUMBER        NOT NULL,
    nombre_clase  VARCHAR2(50)  NOT NULL,
    dia_semana    VARCHAR2(15)  NOT NULL,
    hora_clase    VARCHAR2(5)   NOT NULL,
    duracion_min  NUMBER        DEFAULT 60 NOT NULL,
    precio        NUMBER(10,2)  NOT NULL,
    estado        VARCHAR2(20)  DEFAULT 'DISPONIBLE' NOT NULL,
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_clases         PRIMARY KEY (clase_id),
    CONSTRAINT fk_cs_clases         FOREIGN KEY (entrenador_id)
                                    REFERENCES cs_entrenadores (entrenador_id),
    CONSTRAINT uq_cs_clases_horario UNIQUE (dia_semana, hora_clase),
    CONSTRAINT ck_cs_clases_estado  CHECK (estado IN ('DISPONIBLE', 'RESERVADA')),
    CONSTRAINT ck_cs_clases_dia     CHECK (dia_semana IN ('LUNES', 'MARTES', 'MIÉRCOLES', 'JUEVES', 'VIERNES', 'SÁBADO')),
    CONSTRAINT ck_cs_clases_nombre  CHECK (nombre_clase IN ('PILATES REFORMER', 'HOT PILATES', 'BARRÉ', 'HIPOPRESIVOS')),
    CONSTRAINT ck_clases_precio     CHECK (precio >= 0),
    CONSTRAINT ck_clases_duracion   CHECK (duracion_min = 60),
    CONSTRAINT ck_cs_clases_hora    CHECK (REGEXP_LIKE(hora_clase, '^\d{2}:\d{2}$'))
);

--Reservas
CREATE TABLE cs_reservas (
    reserva_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id  NUMBER        NOT NULL,
    clase_id    NUMBER        NOT NULL,
    monto_total NUMBER(12,2)  NOT NULL,
    estado      VARCHAR2(10)  DEFAULT 'ACTIVA' NOT NULL,
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_reservas        PRIMARY KEY (reserva_id),
    CONSTRAINT fk_cs_clie_reservas   FOREIGN KEY (cliente_id) 
                                     REFERENCES cs_clientes (cliente_id),
    CONSTRAINT fk_cs_clase_reservas  FOREIGN KEY (clase_id)  
                                     REFERENCES cs_clases (clase_id),
    CONSTRAINT ck_cs_reservas_monto  CHECK (monto_total >= 0),
    CONSTRAINT ck_cs_reservas_estado CHECK (estado IN ('ACTIVA', 'CANCELADA', 'TERMINADA', 'NO LLEGÓ'))
);

--Pagos
CREATE TABLE cs_pagos (
    pago_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id NUMBER       NOT NULL,
    fecha_pago DATE         NOT NULL,
    monto_pago NUMBER(12,2) NOT NULL,
    canal_pago VARCHAR2(30) DEFAULT 'TARJETA DE CRÉDITO' NOT NULL,
    estado     VARCHAR2(10) DEFAULT 'PAGADO' NOT NULL,
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_pagos         PRIMARY KEY (pago_id),
    CONSTRAINT fk_cs_pagos_reservas FOREIGN KEY (reserva_id) 
                                    REFERENCES cs_reservas (reserva_id),
    CONSTRAINT uq_cs_pagos_reserva  UNIQUE (reserva_id),
    CONSTRAINT ck_cs_pagos_monto    CHECK (monto_pago >= 0),
    CONSTRAINT ck_cs_pagos_estado   CHECK (estado IN ('PAGADO', 'PENDIENTE')),
    CONSTRAINT ck_cs_pagos_canal    CHECK (canal_pago IN ('TARJETA DE CRÉDITO', 'TRANSFERENCIA', 'EFECTIVO'))
);

--Notas Cancelación
CREATE TABLE cs_notas_cancelacion (
    nota_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id       NUMBER        NOT NULL,
    fecha_nota       DATE          NOT NULL,
    monto_devolucion NUMBER(12,2)  NOT NULL,
    motivo           VARCHAR2(30)  DEFAULT 'CANCELACION' NOT NULL,
    --CONTRAINTS/RESTRICCIONES
    CONSTRAINT pk_cs_notas         PRIMARY KEY (nota_id),
    CONSTRAINT fk_cs_notas_reservas FOREIGN KEY (reserva_id) 
                                    REFERENCES cs_reservas (reserva_id),
    CONSTRAINT ck_cs_nota_monto     CHECK (monto_devolucion >= 0)
);

ALTER TABLE cs_reservas
ADD fecha_reserva DATE NOT NULL;

ALTER TABLE cs_reservas ADD CONSTRAINT uq_cs_reservas_clase_fecha 
UNIQUE (clase_id, fecha_reserva);

ALTER TABLE cs_entrenadores ADD (
    especialidad VARCHAR2(50),
    experiencia_anios NUMBER,
    formacion VARCHAR2(100)
);

COMMIT;